export const MOCK_LEGENDS = {
  kota: [
    { rank: 1, user: "Pak Adi", avatar: "🏆", area: "Tangsel", titles: 7, pts: 9800 },
    { rank: 2, user: "H. Surya", avatar: "🎖️", area: "Tangsel", titles: 5, pts: 7200 },
    { rank: 3, user: "Mang Dul", avatar: "🎣", area: "Cirebon", titles: 4, pts: 6100 },
  ],
  provinsi: [
    { rank: 1, user: "Pak Adi", avatar: "🏆", area: "Banten", titles: 7, pts: 9800 },
    { rank: 2, user: "Koh Aan", avatar: "🐉", area: "Jabar", titles: 6, pts: 8400 },
    { rank: 3, user: "H. Surya", avatar: "🎖️", area: "Banten", titles: 5, pts: 7200 },
  ],
  nasional: [
    { rank: 1, user: "Koh Aan", avatar: "🐉", area: "Jabar", titles: 6, pts: 8400 },
    { rank: 2, user: "Pak Adi", avatar: "🏆", area: "Banten", titles: 7, pts: 9800 },
    { rank: 3, user: "Bang Topan", avatar: "⚡", area: "Sumut", titles: 5, pts: 7900 },
  ],
};

export const MOCK_STRIKES = [
  {
    id: "m1",
    user: "Pak Adi",
    avatar: "🏆",
    loc: "Tangsel",
    disc: "galatama",
    event: "Galatama Mas — Kolam Berkah Jaya",
    fish: "Ikan Mas",
    weight: 4.2,
    place: 1,
    prize: "Rp 5.000.000 + Trofi",
    gear: "NF Strike Series + pelet",
    verified: true,
    xp: 500,
    likes: 128,
    proof: { kolam: true, juara: true, hadiah: true },
    time: "1 hari lalu",
  },
  {
    id: "m2",
    user: "Bintang_Angler",
    avatar: "🦈",
    loc: "Cirebon",
    disc: "casting",
    event: "Casting Gabus Open — Rawa Kebon",
    fish: "Gabus",
    weight: 2.1,
    place: 1,
    prize: "Reel + Rp 1.000.000",
    gear: "Magic Strike NF",
    verified: true,
    xp: 500,
    likes: 96,
    proof: { kolam: true, juara: true, hadiah: true },
    time: "2 hari lalu",
  },
];
