export const MOCK_CAUGHT = [
  {
    id: 1,
    user: "Mang Dul",
    avatar: "🎣",
    disc: "galatama",
    fish: "Ikan Mas",
    weight: 2.4,
    gear: "Essen Ikan Mas NF + pelet",
    spot: "Galatama Sumber",
    time: "2 jam lalu",
    likes: 34,
    emoji: "🐟",
  },
  {
    id: 2,
    user: "Bintang_Angler",
    avatar: "🦈",
    disc: "casting",
    fish: "Gabus",
    weight: 1.8,
    gear: "NF Strike Series",
    spot: "Rawa Kebon",
    time: "5 jam lalu",
    likes: 28,
    emoji: "🐍",
  },
  {
    id: 3,
    user: "Sampriatna",
    avatar: "👑",
    disc: "kiloan",
    fish: "Bawal",
    weight: 3.1,
    gear: "Magic Strike NF",
    spot: "Kolam Gebrus Tukmudal",
    time: "kemarin",
    likes: 51,
    emoji: "🐠",
  },
  {
    id: 4,
    user: "Koh Aan",
    avatar: "🐉",
    disc: "micro",
    fish: "Wader",
    weight: 0.02,
    gear: "Kail micro #26 + kroto",
    spot: "Sungai jernih",
    time: "kemarin",
    likes: 41,
    emoji: "🐟",
  },
];
